/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zu;

import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;
import java.util.stream.Collectors;

import zu.classes.*;


public class App {
    public static Set<Laptop> laptops = new HashSet<>();
    public static Color filterColor;
    public static Brand filterBrand;

    public static void getData() {
        laptops.add(new Laptop(Brand.LG, Color.BLACK, "HS1411", 100000.99));
        laptops.add(new Laptop(Brand.SAMSUNG, Color.WHITE, "HS1311", 150000.99));
        laptops.add(new Laptop(Brand.APPLE, Color.MULTICOLOR, "HS1410", 200000.99));
        laptops.add(new Laptop(Brand.APPLE, Color.BLACK, "HS1401", 100000.99));
        laptops.add(new Laptop(Brand.SAMSUNG, Color.WHITE, "HS2411", 200000.99));
    }

    public static void showAllAction() {
        System.out.println(laptops.stream()
            .filter(laptop -> laptop.filterColor(filterColor) && laptop.filterBrand(filterBrand))
            .collect(Collectors.toList()));
    }
    
    public static void filterColorAction() {
        Scanner scanner = new Scanner(System.in); 
        for (Color color : Color.values()) { 
            System.out.println(color); 
        }
        filterColor = Color.valueOf(scanner.nextLine());
    }

    public static void filterBrandAction() {
        Scanner scanner = new Scanner(System.in); 
        for (Brand brand : Brand.values()) { 
            System.out.println(brand);
        }
        filterBrand = Brand.valueOf(scanner.nextLine());
    }

    public static void filterResetAction() {
        filterColor = null;
        filterBrand = null;
    }

    public static void main(String[] args) {
        int action;
        Scanner scanner = new Scanner(System.in);
        getData();
        
        do {
            System.out.println("Введите команду");
            System.out.println("1 - показать");
            System.out.println("2 - выбрать бренд");
            System.out.println("3 - выбрать цвет");
            System.out.println("9 - сбросить фильтр");
            System.out.println("0 - выйти");
            action = Integer.valueOf(scanner.nextLine());
            switch (action) {
                case  (1):
                    showAllAction();
                    break;
                case  (2):
                    filterBrandAction();
                    break;    
                case  (3):
                    filterColorAction();
                    break;
                case  (9):
                    filterResetAction();
                    break;    
                default:
                    if (action != 0)
                        System.out.println("Неверная команда");
                    break;
            }
        } while(action != 0);
    }
}